### ISSUE TITLE
Initial Project created from Atlas App Services Results in Disconnected Socket

### ISSUE THREAD

**Issue by ngoctranfire** [realm/realm-dart#1471]
### What happened?
Note: I've already allow-listed my remote IP address as well too.

When I follow the instructions and setup the project and run it, I always get this error:

```
Error:


error handling "bind" message: error getting sync status from metadata store: error getting initial sync status: mongo: no documents in result

Logs:

[
  "Connection was active for: 1s"
]
Function Call Location:

SG

Remote IP Address:

126.62.64.148

SDK:

Dart v1.6.1

Framework:

Flutter v3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "ios_arm64"

Platform:

iOS vVersion 17.2.1 (Build 21C66)
```

On my Client Side Logs, it shows this on Flutter's Device:

```
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           10.7s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:64261/js8xCaiL568=/ws
flutter: To see your data in Atlas, follow this link:https://cloud.mongodb.com/links/65a4a4d0e591c818117a2c6b/explorer/AtlasCluster/database/collection/find
flutter: 2024-01-15T03:17:01.227284: [ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid username/password
flutter: To see your data in Atlas, follow this link: https://cloud.mongodb.com/links/65a4a4d0e591c818117a2c6b/explorer/AtlasCluster/database/collection/find
flutter: 2024-01-15T03:17:05.106130: [INFO] Realm: Realm sync client ([realm-core-13.24.0])
flutter: 2024-01-15T03:17:05.106291: [INFO] Realm: Platform: iOS Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64
flutter: 2024-01-15T03:17:05.107431: [INFO] Realm: Connection[1]: Session[1]: Binding '/Users/ngoc/Library/Developer/CoreSimulator/Devices/F8FBCB59-4144-4D6E-80D8-23F6338B7FF5/data/Containers/Data/Application/368D5A44-0684-4FB9-9854-B9BACB2FDBB4/Documents/mongodb-realm/application-0-hkiwf/65a4a8839ab1876fdba3bdea/default.realm' to ''
flutter: 2024-01-15T03:17:05.107543: [INFO] Realm: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true
flutter: 2024-01-15T03:17:05.107659: [INFO] Realm: Connection[1]: Connecting to 'wss://ws.ap-southeast-1.aws.realm.mongodb.com:443/api/client/v2.0/app/application-0-hkiwf/realm-sync'
flutter: 2024-01-15T03:17:05.214003: [INFO] Realm: Connected to endpoint '18.136.255.153:443' (from '192.168.0.92:64287')
flutter: 2024-01-15T03:17:05.604978: [INFO] Realm: Connection[1]: Connected to app services with request id: "65a5143136f40152d3b2713b"
flutter: 2024-01-15T03:17:05.758134: [INFO] Realm: Connection[1]: Closing the websocket with error code=WebSocket: OK, message='', was_clean=true
flutter: 2024-01-15T03:17:09.934501: [ERROR] Realm: Reading failed: End of input
flutter: 2024-01-15T03:17:09.935224: [INFO] Realm: Connection[1]: Closing the websocket with error code=WebSocket: Read Error, message='End of input', was_clean=false
flutter: 2024-01-15T03:17:09.935701: [INFO] Realm: Connection[1]: Connection closed due to transient error: ConnectionClosed: End of input
flutter: 2024-01-15T03:17:10.906101: [INFO] Realm: Connection[1]: Connecting to 'wss://ws.ap-southeast-1.aws.realm.mongodb.com:443/api/client/v2.0/app/application-0-hkiwf/realm-sync'

```

I really want to try and use Realm for my Project, but I can't seem to even get the sample project running. I'd love for some advice!

### Repro steps
Just start the app-services project and the realm guide for flutter.

### Version
1.6.1

### What Atlas Services are you using?
Both Atlas Device Sync and Atlas App Services

### What type of application is this?
Flutter Application

### Client OS and version
iOS Version 17.2.1 

### Stacktrace of the exception/crash you're getting
```shell
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           10.7s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:64261/js8xCaiL568=/ws
flutter: To see your data in Atlas, follow this link:https://cloud.mongodb.com/links/65a4a4d0e591c818117a2c6b/explorer/AtlasCluster/database/collection/find
flutter: 2024-01-15T03:17:01.227284: [ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid username/password
flutter: To see your data in Atlas, follow this link: https://cloud.mongodb.com/links/65a4a4d0e591c818117a2c6b/explorer/AtlasCluster/database/collection/find
flutter: 2024-01-15T03:17:05.106130: [INFO] Realm: Realm sync client ([realm-core-13.24.0])
flutter: 2024-01-15T03:17:05.106291: [INFO] Realm: Platform: iOS Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64
flutter: 2024-01-15T03:17:05.107431: [INFO] Realm: Connection[1]: Session[1]: Binding '/Users/ngoc/Library/Developer/CoreSimulator/Devices/F8FBCB59-4144-4D6E-80D8-23F6338B7FF5/data/Containers/Data/Application/368D5A44-0684-4FB9-9854-B9BACB2FDBB4/Documents/mongodb-realm/application-0-hkiwf/65a4a8839ab1876fdba3bdea/default.realm' to ''
flutter: 2024-01-15T03:17:05.107543: [INFO] Realm: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true
flutter: 2024-01-15T03:17:05.107659: [INFO] Realm: Connection[1]: Connecting to 'wss://ws.ap-southeast-1.aws.realm.mongodb.com:443/api/client/v2.0/app/application-0-hkiwf/realm-sync'
flutter: 2024-01-15T03:17:05.214003: [INFO] Realm: Connected to endpoint '18.136.255.153:443' (from '192.168.0.92:64287')
flutter: 2024-01-15T03:17:05.604978: [INFO] Realm: Connection[1]: Connected to app services with request id: "65a5143136f40152d3b2713b"
flutter: 2024-01-15T03:17:05.758134: [INFO] Realm: Connection[1]: Closing the websocket with error code=WebSocket: OK, message='', was_clean=true
flutter: 2024-01-15T03:17:09.934501: [ERROR] Realm: Reading failed: End of input
flutter: 2024-01-15T03:17:09.935224: [INFO] Realm: Connection[1]: Closing the websocket with error code=WebSocket: Read Error, message='End of input', was_clean=false
flutter: 2024-01-15T03:17:09.935701: [INFO] Realm: Connection[1]: Connection closed due to transient error: ConnectionClosed: End of input
flutter: 2024-01-15T03:17:10.906101: [INFO] Realm: Connection[1]: Connecting to 'wss://ws.ap-southeast-1.aws.realm.mongodb.com:443/api/client/v2.0/app/application-0-hkiwf/realm-sync'
```

**Comment by nielsenko** [comment]
@ngoctranfire Thank you for trying out Realm. 

I see that it complains about the authentication:
```
flutter: 2024-01-15T03:17:01.227284: [ERROR] Realm: App: log_in_with_credentials failed: 401 message: invalid username/password
```
Does that ring a bell? Also, did you look into the error log?
https://cloud.mongodb.com/links/65a4a4d0e591c818117a2c6b/explorer/AtlasCluster/database/collection/find

**Comment by ngoctranfire** [comment]
@nielsenko The first time I actually tried it yes, it did result in incorrect credentials. Please ignore that. The second time, I got the correct credentials and got into the app, but the same thing still happened.

**Comment by nirinchev** [comment]
Hey, we got a response from the server team - looks like something went wrong initializing sync for your app. They'll investigate it, but in the meantime, you can try to terminate and reenable sync, which should resolve it.

**Comment by ngoctranfire** [comment]
@nirinchev I actually tried that too but it still never recovered. I still have the same issue.

**Comment by tkaye407** [comment]
Hi, can you terminate sync, then deploy, then enable sync and deploy. I suspect looking at your deployment history that you terminated sync, then enabled sync, then clicked deploy (which was a no-op).
